<!-- 
  Filippo Finke
  Pagina principale
-->
<!DOCTYPE html>
<html lang="it">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Filippo Finke">

  <title>HackerLab - Home</title>

  <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/global.css" rel="stylesheet">
  <link href="/css/blog-home.css" rel="stylesheet">

</head>

<body>

  <!-- Navigazione -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">HackerLab <small>di Filippo Finke</small></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <!-- Controlla se l'utente ha eseguito l'accesso -->
          <?php if($permission !== null): ?>
          <li class="nav-item">
            <a class="nav-link" href="/profile">Profilo</a>
          </li>
          <?php else: ?>
          <li class="nav-item">
            <a class="nav-link" href="/register">Registrati</a>
          </li>
          <?php endif; ?>
          <!-- Se l'utente è amministratore mostra i collegamenti al pannello amministrativo -->
          <?php if($permission === "administrator"): ?>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropDown" role="button" data-toggle="dropdown">
              Pannello di amministrazione
            </a>
            <div class="dropdown-menu" aria-labelledby="dropDown">
              <a class="dropdown-item" href="/admin/articles">Articoli</a>
              <a class="dropdown-item" href="/admin/users">Utenti</a>
            </div>
          </li>
          <?php endif; ?>
          <!-- Controlla se l'utente ha eseguito l'accesso -->
          <?php if($permission !== null): ?>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Esci</a>
          </li>
          <?php endif; ?>
          <li class="nav-item">
            <a class="nav-link" onclick="if(confirm('Sicuro di voler eseguire un reset del database?')) { window.location.href= '/reset';}">Reset database</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Contenuto della pagina -->
  <div class="container main-container">
    <div class="row">
      <div class="col-md-8">
        <!-- Controlla se l'utente è arrivato alla pagina attraverso un'altra pagina o una ricerca -->
        <?php if(isset($_GET["search"]) && $_GET["search"] != ""): ?>
        <h1 class="my-4">Ricerca per <?php echo htmlspecialchars($_GET["search"]); ?></h1>
        <?php elseif(isset($page) && $page != 0): ?>
        <h1 class="my-4">Pagina <?php echo ($page + 1); ?></h1>
        <?php else: ?>
        <h1 class="my-4">Ultimi articoli</h1>
        <?php endif; ?>

        <!-- Se è presente un errore, mostralo all'utente -->
        <?php if(isset($_SESSION["big_error"])): ?>
        <div class="alert alert-danger" role="alert">
          <?php echo $_SESSION["big_error"]; ?>
          <?php unset($_SESSION["big_error"]); ?>
        </div>
        <?php endif; ?>

        <!-- Controlla la presenza di articoli -->
        <?php if(count($articles) == 0): ?>
        <div class="text-center">
            <h4>Non è presente nessun articolo.</h4>
            <button class="btn btn-primary" data-toggle="modal" data-target="#addArticle">Contribuisci a HackerLab</button>
        </div>
        <br>
        <?php endif;?>

        <!-- Stampa gli articoli presenti nel sito -->
        <?php foreach($articles as $article): ?>
        <div class="card mb-4">
          <!-- Se l'articolo possiede un immagine, stampa il tag img -->
          <?php if($article["image"] != null): ?>
          <img class="article-image" src="/image/?file_name=<?php echo $article["image"]; ?>">
          <?php endif; ?>
          <!-- Stampa delle varie informazioni dell'articolo -->
          <div class="card-body">
            <h2 class="card-title"><?php echo $article["title"]; ?></h2>
            <a href="/post/<?php echo $article["id"]; ?>" class="btn btn-primary">Vai all'articolo &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Pubblicato il <?php echo date("d.m.Y", strtotime($article["created_at"])); ?> da
            <a href="/profile/<?php echo $article["user_id"]; ?>"><?php echo $article["full_name"] ?? "eliminato"; ?></a>
          </div>
        </div>
        <?php endforeach; ?>

        <!-- Paginazione -->
        <ul class="pagination justify-content-center mb-4">
          <!-- Calcola le pagine precedenti e successive -->
          <?php 
          $oldpage = $page - 1;
          if($oldpage < 0) $oldpage = 0;
          $search = "";
          if(isset($_GET["search"])) $search = "?search=".$_GET["search"];
          ?>
          <li class="page-item <?php if($page == 0) echo "disabled"; ?>">
            <a class="page-link" href="/page/<?php echo $oldpage.$search; ?>">&larr; Pagina precedente</a>
          </li>
          <li class="page-item <?php if($page == $maxPage) echo "disabled"; ?>">
            <a class="page-link" href="/page/<?php echo ($page + 1).$search; ?>">Prossima pagina &rarr;</a>
          </li>
        </ul>

      </div>

      <div class="col-md-4">
        <div class="card my-4">
          <h5 class="card-header">Cerca</h5>
          <div class="card-body">
            <form method="GET" action="/">
              <div class="input-group">
                <input type="text" class="form-control" name="search" placeholder="Ricerca..." required>
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="submit">Cerca!</button>
                </span>
              </div>
            </form>
          </div>
        </div>
        <!-- Se l'utente non ha eseguito l'accesso mostra la schermata di login -->
        <?php if($permission === null): ?>
        <div class="card my-4">
          <h5 class="card-header">Accedi</h5>
          <div class="card-body">
            <div class="tab-content" id="tabs">
              <div class="tab-pane fade show active" id="login" role="tabpanel">
                <form method="POST" action="/login">
                  <div class="form-group">
                    <label for="email">Indirizzo email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                  </div>
                  
                  <!-- Se è presente un errore, mostralo all'utente -->
                  <?php if(isset($_SESSION["error"])): ?>
                  <div class="alert alert-danger" role="alert">
                    <?php echo $_SESSION["error"]; ?>
                    <?php unset($_SESSION["error"]); ?>
                  </div>
                  <?php endif; ?>

                  <!-- Se è presente un messaggio di successo, mostralo all'utente -->
                  <?php if(isset($_SESSION["success"])): ?>
                    <div class="alert alert-success" role="alert">
                      <?php echo $_SESSION["success"]; ?>
                      <?php unset($_SESSION["success"]); ?>
                    </div>
                  <?php endif; ?>
                  <div class="text-center">
                    <button type="submit" class="btn btn-secondary">Accedi</button>
                    <br>
                    oppure
                    <a href="/register">Registrati</a>
                    <hr>
                    <a data-toggle="tab" href="#forgot-password">Password dimenticata?</a>
                  </div>
                </form>
              </div>
              <div class="tab-pane fade" id="forgot-password" role="tabpanel">
                <form action="/reset" method="POST">
                  <div class="form-group">
                    <label for="email_reset">Indirizzo email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email" required>
                  </div>
                  <div class="text-center">
                    <button type="submit" class="btn btn-secondary">Recupera la password</button>
                    <hr>
                    <a data-toggle="tab" href="#login">Accedi</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        
        <?php else: ?>

        <div class="card my-4">
          <h5 class="card-header">Accesso eseguito</h5>
          <div class="card-body">
            <!-- Stampa il nome completo dell'utente loggato, se non presente stampa 'full_name' -->
            Bevenuto <b><?php echo $_SESSION["user"]["full_name"] ?? "full_name"; ?></b>
            <br>
            <br>
            <div class="text-center">
              <button class="btn btn-secondary" data-toggle="modal" data-target="#addArticle">Pubblica un articolo</button>
            </div>
          </div>
        </div>
        <?php endif; ?>
      </div>
    </div>

  </div>

  <!-- Modal di reset della password -->
  <div class="modal fade" id="resetModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Imposta la tua password</h5>
        </div>
        <form action="/reset_password" method="POST">
          <div class="modal-body">
              <div class="form-group">
                <label for="reset_password">Password</label>
                <input type="hidden" class="form-control" id="reset_token" name="reset_token">
                <input type="password" class="form-control" name="password" placeholder="Password">
              </div>
              <div class="form-group">
                <label for="reset_password_repeat">Ripeti password</label>
                <input type="password" class="form-control" name="repeat_password" placeholder="Password">
              </div>
              <!-- Se è presente un errore, mostralo all'utente -->
              <?php if(isset($_SESSION["reset_password"])): ?>
              <div class="alert alert-danger" role="alert">
                <?php echo $_SESSION["reset_password"]; ?>
                <?php unset($_SESSION["reset_password"]); ?>
              </div>
              <?php endif; ?>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-secondary">Imposta password</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Modal di pubblicazione di un articolo -->
  <div class="modal fade" id="addArticle" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Pubblica un articolo</h5>
        </div>
        <form action="/post" method="POST" enctype="multipart/form-data">
          <div class="modal-body">
              <div class="form-group">
                <input type="text" class="form-control" name="title" placeholder="Titolo" maxlength="255" required>
              </div>
              <div class="form-group">
                <label for="image">Sfondo</label>
                <input type="file" class="form-control-file" name="image">
              </div>
              <div class="form-group">
                <textarea class="form-control" name="content" rows="10" placeholder="Contenuto" maxlength="2000" required></textarea>
                <code>Sono permessi i tag html: h1, ul, li, a, img, code, br</code>
              </div>
          </div>
          <div class="modal-footer">
            <!-- Se è presente un errore, mostralo all'utente -->
            <?php if(isset($_SESSION["article_error"])): ?>
            <div class="alert alert-danger" role="alert">
              <?php echo $_SESSION["article_error"]; ?>
              <?php unset($_SESSION["article_error"]); ?>
            </div>
            <?php endif; ?>
            <button type="submit" class="btn btn-secondary">Pubblica</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="/vendor/jquery/jquery.min.js"></script>
  <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
<script>
let params = new URLSearchParams(window.location.search);
let token = params.get('reset_token');
// Se è presente il parametro di recupero password mostra il modale.
if(token != null) {
  $("#reset_token").val(token);
  $("#resetModal").modal({backdrop: 'static', keyboard: false});
}
// Se è presente il parametro di pubblicazione di un articolo mostra il modale.
if(params.get('publish_article') != null) {
  $("#addArticle").modal('toggle');
}
</script>
</html>
