<!DOCTYPE html>
<html lang="it">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Filippo Finke">

  <title>HackerLab - Home</title>

  <!-- Bootstrap core CSS -->
  <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/css/blog-home.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">HackerLab</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <?php if($permission !== null): ?>
          <li class="nav-item">
            <a class="nav-link" href="/profile">Profilo</a>
          </li>
          <?php else: ?>
          <li class="nav-item">
            <a class="nav-link" href="/register">Registrati</a>
          </li>
          <?php endif; ?>
          <?php if($permission === "administrator"): ?>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropDown" role="button" data-toggle="dropdown">
              Pannello di amministrazione
            </a>
            <div class="dropdown-menu" aria-labelledby="dropDown">
              <a class="dropdown-item" href="/admin/articoli">Articoli</a>
              <a class="dropdown-item" href="/admin/utenti">Utenti</a>
            </div>
          </li>
          <?php endif; ?>
          <?php if($permission !== null): ?>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Esci</a>
          </li>
          <?php endif; ?>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-md-8">
        <?php if(isset($_GET["search"]) && $_GET["search"] != ""): ?>
        <h1 class="my-4">Ricerca per <?php echo htmlspecialchars($_GET["search"]); ?></h1>
        <?php else: ?>
        <h1 class="my-4">Ultimi articoli</h1>
        <?php endif; ?>

        <?php if(isset($_SESSION["big_error"])): ?>
        <div class="alert alert-danger" role="alert">
          <?php echo $_SESSION["big_error"]; ?>
          <?php unset($_SESSION["big_error"]); ?>
        </div>
        <?php endif; ?>

        <?php foreach($articles as $article): ?>
        <div class="card mb-4">
          <img class="card-img-top" src="<?php echo $article["image"]; ?>">
          <div class="card-body">
            <h2 class="card-title"><?php echo $article["title"]; ?></h2>
            <a href="/post/<?php echo $article["id"]; ?>" class="btn btn-primary">Vai all'articolo &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Pubblicato il <?php echo date("d.m.Y", strtotime($article["created_at"])); ?> da
            <a href="/profile/<?php echo $article["user_id"]; ?>"><?php echo $article["full_name"]; ?></a>
          </div>
        </div>
        <?php endforeach; ?>

        <!-- Pagination -->
        <ul class="pagination justify-content-center mb-4">
          <?php 
          $oldpage = $page - 1;
          if($oldpage < 0) $oldpage = 0;
          $search = "";
          if(isset($_GET["search"])) $search = "?search=".$_GET["search"];
          ?>
          <li class="page-item <?php if($page == 0) echo "disabled"; ?>">
            <a class="page-link" href="/page/<?php echo $oldpage.$search; ?>">&larr; Recenti</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="/page/<?php echo ($page + 1).$search; ?>">Vecchi &rarr;</a>
          </li>
        </ul>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Cerca</h5>
          <div class="card-body">
            <form method="GET" action="/">
              <div class="input-group">
                <input type="text" class="form-control" name="search" placeholder="Ricerca...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="submit">Cerca!</button>
                </span>
              </div>
            </form>
          </div>
        </div>
        <?php if($permission === null): ?>
        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Accedi</h5>
          <div class="card-body">
            <div class="tab-content" id="tabs">
              <div class="tab-pane fade show active" id="login" role="tabpanel">
                <form method="POST" action="/login">
                  <div class="form-group">
                    <label for="email">Indirizzo email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                  </div>
                  <?php if(isset($_SESSION["error"])): ?>
                  <div class="alert alert-danger" role="alert">
                    <?php echo $_SESSION["error"]; ?>
                    <?php unset($_SESSION["error"]); ?>
                  </div>
                  <?php endif; ?>

                  <?php if(isset($_SESSION["success"])): ?>
                    <div class="alert alert-success" role="alert">
                      <?php echo $_SESSION["success"]; ?>
                      <?php unset($_SESSION["success"]); ?>
                    </div>
                  <?php endif; ?>
                  <div class="text-center">
                    <button type="submit" class="btn btn-secondary">Accedi</button>
                    <br>
                    oppure
                    <a href="/register">Registrati</a>
                    <hr>
                    <a data-toggle="tab" href="#forgot-password">Password dimenticata?</a>
                  </div>
                </form>
              </div>
              <div class="tab-pane fade" id="forgot-password" role="tabpanel">
                <form action="/reset" method="POST">
                  <div class="form-group">
                    <label for="email_reset">Indirizzo email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                  </div>
                  <div class="text-center">
                    <button type="submit" class="btn btn-secondary">Recupera la password</button>
                    <hr>
                    <a data-toggle="tab" href="#login">Accedi</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        
        <?php else: ?>

        <div class="card my-4">
          <h5 class="card-header">Accesso eseguito</h5>
          <div class="card-body">
            Bevenuto <b><?php echo $_SESSION["user"]["full_name"] ?? "full_name"; ?></b>
            <br>
            <br>
            <div class="text-center">
              <button class="btn btn-secondary" data-toggle="modal" data-target="#addArticle">Pubblica un articolo</button>
            </div>
          </div>
        </div>

        <?php endif; ?>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; HackerLab 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <div class="modal fade" id="resetModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Imposta la tua password</h5>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" id="reset_token" disabled>
            </div>
            <div class="form-group">
              <label for="reset_password">Password</label>
              <input type="password" class="form-control" id="reset_password" placeholder="Password">
            </div>
            <div class="form-group">
              <label for="reset_password_repeat">Ripeti password</label>
              <input type="password" class="form-control" id="reset_password_repeat" placeholder="Password">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary">Imposta password</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="addArticle" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Pubblica un articolo</h5>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="text" class="form-control" id="title" placeholder="Titolo">
            </div>
            <div class="form-group">
              <label for="image">Sfondo</label>
              <input type="file" class="form-control-file" id="image">
            </div>
            <div class="form-group">
              <textarea class="form-control" id="content" rows="10" placeholder="Contenuto"></textarea>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary">Imposta password</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  <script src="/vendor/jquery/jquery.min.js"></script>
  <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
<script>
let params = new URLSearchParams(window.location.search);
let token = params.get('reset_password');
if(token != null) {
  $("#reset_token").val(token);
  $("#resetModal").modal({backdrop: 'static', keyboard: false});
}
</script>
</html>
