<!DOCTYPE html>
<html lang="it">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Filippo Finke">

  <title>HackerLab - Come installare Windows10</title>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="css/blog-post.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">HackerLab</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/profile">Profilo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/register">Registrati</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin">Pannello di amministrazione</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">Come installare Windows10</h1>

        <!-- Author -->
        <p class="lead">
          di
          <a href="/profile">Filippo Finke</a>
        </p>

        <hr>

        <!-- Date/Time -->
        <p>Pubblicato il 1 gennaio 2019 alle ore 12:22</p>

        <hr>

        <!-- Preview Image -->
        <div class="text-center">
          <img style="max-height: 300px;" src="https://upload.wikimedia.org/wikipedia/it/5/51/Windows_10_1903_Desktop.png">
        </div>
        <hr>

        <!-- Post Content -->

        <p>
          <h1>Windows10</h1>
          Per eseguire un installazione di Windows10 ti serviranno le seguenti...
          <ul>
            <li>Test</li>
          </ul>
          <a href="#">Test</a>
        </p>

        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Lascia un commento: </h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="2"></textarea>
              </div>
              <button type="submit" class="btn btn-secondary">Invia</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        <div class="media mb-4">
          <img style="max-width: 50px;" class="d-flex mr-3 rounded-circle" src="/images/user.png">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="/profile">Filippo Finke</a>
              <small>1 gennaio 2019</small>
            </h5>
            Guida utilissima!
          </div>
        </div>

        <div class="media mb-4">
          <img style="max-width: 50px;" class="d-flex mr-3 rounded-circle" src="/images/user.png">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="/profile">Filippo Finke</a>
              <small>1 gennaio 2019</small>
            </h5>
            Test!
          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Cerca</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Ricerca...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Cerca!</button>
              </span>
            </div>
          </div>
        </div>

        <div class="card my-4">
          <h5 class="card-header">Accesso eseguito</h5>
          <div class="card-body">
            Bevenuto Filippo Finke!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; HackerLab 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>
