<!DOCTYPE html>
<html lang="it">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Filippo Finke">

  <title>HackerLab - <?php echo $user["full_name"]; ?></title>

  <!-- Bootstrap core CSS -->
  <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/css/blog-home.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/">HackerLab</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/profile">Profilo</a>
          </li>
          <?php if($permission === "administrator"): ?>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="dropDown" role="button" data-toggle="dropdown">
              Pannello di amministrazione
            </a>
            <div class="dropdown-menu" aria-labelledby="dropDown">
              <a class="dropdown-item" href="/admin/articles">Articoli</a>
              <a class="dropdown-item" href="/admin/users">Utenti</a>
            </div>
          </li>
          <?php endif; ?>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Esci</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Blog Entries Column -->
      <div class="col-md-8">

        <h1 class="my-4">
          Articoli di <?php echo $user["full_name"]; ?><br>
          <?php if($permission === "administrator"): ?>
            <small><?php echo $user["email"]; ?></small>
          <?php endif; ?>
        </h1>
        <?php if(count($articles) == 0): ?>
        <h4>Nessun articolo.</h4>
        <?php endif; ?>
        <?php foreach($articles as $article): ?>
        <div class="card mb-4">
          <img class="card-img-top" src="<?php echo $article["image"]; ?>">
          <div class="card-body">
            <h2 class="card-title"><?php echo $article["title"]; ?></h2>
            <a href="/post/<?php echo $article["id"]; ?>" class="btn btn-primary">Vai all'articolo &rarr;</a>
          </div>
          <div class="card-footer text-muted">
            Pubblicato il <?php echo date("d.m.Y", strtotime($article["created_at"])); ?> da
            <a href="/profile/<?php echo $article["user_id"]; ?>"><?php echo $user["full_name"]; ?></a>
          </div>
        </div>
        <?php endforeach; ?>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Cerca</h5>
          <div class="card-body">
            <form method="GET" action="/">
              <div class="input-group">
                <input type="text" class="form-control" name="search" placeholder="Ricerca...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="submit">Cerca!</button>
                </span>
              </div>
            </form>
          </div>
        </div>

        <div class="card my-4">
          <h5 class="card-header">Accesso eseguito</h5>
          <div class="card-body">
            Bevenuto <b><?php echo $_SESSION["user"]["full_name"] ?? "full_name"; ?></b>
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; HackerLab 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/vendor/jquery/jquery.min.js"></script>
  <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>
